### ISSUE TITLE
how do i get ARCHE.ttl from my basrow tables

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-2-baserow#4]
i guess you have some script but its not mentioned in the readme and it seems not to be part of the code

**Comment by linxOD** [comment]
This repo is only meant to parse arche and vocabs schemas, create tables and upload it with a preset schema. Everything else should be handled seperately. Currently I use this repo. Once, I finalized the first part I will create a common more generalized repo. https://github.com/Auden-Musulin-Papers/amp-archive
